// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Start a thread-scoped local shell command.
 */
export type LocalShellStartParams = { 
/**
 * Target thread id.
 */
threadId: string, 
/**
 * Shell command text to execute.
 */
command: string, };
